MOCK_LISTINGS = [
    {
        "source": "ebay",
        "external_id": "mock-001",
        "title": "2003-04 Upper Deck LeBron James Rookie Card #301 PSA 9",
        "price": 850.00,
        "listing_url": "https://ebay.com",
        "image_url": "https://i.ebayimg.com/images/g/placeholder/s-l500.jpg",
        "seller_name": "cardseller99",
        "condition": "Graded",
        "is_sold": False,
    },
    {
        "source": "ebay",
        "external_id": "mock-002",
        "title": "2003-04 Topps Chrome LeBron James Rookie RC #111 BGS 8.5",
        "price": 420.00,
        "listing_url": "https://ebay.com",
        "image_url": "https://i.ebayimg.com/images/g/placeholder/s-l500.jpg",
        "seller_name": "hoopscards",
        "condition": "Graded",
        "is_sold": False,
    },
    {
        "source": "ebay",
        "external_id": "mock-003",
        "title": "2003-04 Bowman Chrome LeBron James Rookie #123 Raw NM-MT",
        "price": 180.00,
        "listing_url": "https://ebay.com",
        "image_url": "https://i.ebayimg.com/images/g/placeholder/s-l500.jpg",
        "seller_name": "sportscardking",
        "condition": "Near Mint",
        "is_sold": False,
    },
    {
        "source": "ebay",
        "external_id": "mock-004",
        "title": "Patrick Mahomes 2017 Panini Prizm Rookie Card PSA 10",
        "price": 310.00,
        "listing_url": "https://ebay.com",
        "image_url": "https://i.ebayimg.com/images/g/placeholder/s-l500.jpg",
        "seller_name": "nflcardshop",
        "condition": "Graded",
        "is_sold": False,
    },
    {
        "source": "ebay",
        "external_id": "mock-005",
        "title": "Charizard 1999 Pokemon Base Set Holo #4 PSA 8",
        "price": 650.00,
        "listing_url": "https://ebay.com",
        "image_url": "https://i.ebayimg.com/images/g/placeholder/s-l500.jpg",
        "seller_name": "pokecards4u",
        "condition": "Graded",
        "is_sold": False,
    },
]

MOCK_SOLD = [
    {"sold_price": 900.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-28"},
    {"sold_price": 820.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-20"},
    {"sold_price": 875.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-15"},
    {"sold_price": 790.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-10"},
    {"sold_price": 950.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-01"},
]
