MOCK_LISTINGS = [
    # NBA
    {
        "source": "ebay", "external_id": "mock-001",
        "title": "2003-04 Upper Deck LeBron James Rookie Card #301 PSA 9",
        "price": 850.00, "listing_url": "https://www.ebay.com/itm/mock001",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "cardseller99", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-002",
        "title": "2003-04 Topps Chrome LeBron James Rookie RC #111 BGS 8.5",
        "price": 420.00, "listing_url": "https://www.ebay.com/itm/mock002",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "hoopscards", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-003",
        "title": "2003-04 Bowman Chrome LeBron James Rookie #123 Raw NM-MT",
        "price": 180.00, "listing_url": "https://www.ebay.com/itm/mock003",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "sportscardking", "condition": "Near Mint", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-004",
        "title": "2009-10 Panini Prizm Stephen Curry Rookie RC PSA 10",
        "price": 3200.00, "listing_url": "https://www.ebay.com/itm/mock004",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "premiumslabs", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-005",
        "title": "2018-19 Panini Prizm Luka Doncic Rookie Silver PSA 10",
        "price": 890.00, "listing_url": "https://www.ebay.com/itm/mock005",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "lukafan77", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-006",
        "title": "1986-87 Fleer Michael Jordan Rookie Card #57 PSA 8",
        "price": 4500.00, "listing_url": "https://www.ebay.com/itm/mock006",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "jordancollector", "condition": "Graded", "is_sold": False,
    },

    # NFL
    {
        "source": "ebay", "external_id": "mock-007",
        "title": "2017 Panini Prizm Patrick Mahomes Rookie RC PSA 10",
        "price": 310.00, "listing_url": "https://www.ebay.com/itm/mock007",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "nflcardshop", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-008",
        "title": "2020 Panini Mosaic Justin Herbert Rookie Silver PSA 10",
        "price": 95.00, "listing_url": "https://www.ebay.com/itm/mock008",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "chargersfan1", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-009",
        "title": "2023 Panini Prizm CJ Stroud Rookie Silver PSA 10",
        "price": 75.00, "listing_url": "https://www.ebay.com/itm/mock009",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "rookiehunter22", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-010",
        "title": "2000 Donruss Tom Brady Rookie Card #230 Raw EX-MT",
        "price": 1200.00, "listing_url": "https://www.ebay.com/itm/mock010",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "goatcards", "condition": "Excellent", "is_sold": False,
    },

    # MLB
    {
        "source": "ebay", "external_id": "mock-011",
        "title": "2011 Bowman Chrome Mike Trout Rookie Auto PSA 10",
        "price": 5500.00, "listing_url": "https://www.ebay.com/itm/mock011",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "baseballvault", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-012",
        "title": "2022 Topps Chrome Julio Rodriguez Rookie PSA 10",
        "price": 45.00, "listing_url": "https://www.ebay.com/itm/mock012",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "mariners_collector", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-013",
        "title": "2023 Topps Update Shohei Ohtani SP Variation Raw NM",
        "price": 28.00, "listing_url": "https://www.ebay.com/itm/mock013",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "dodgers_cards", "condition": "Near Mint", "is_sold": False,
    },

    # Pokemon
    {
        "source": "ebay", "external_id": "mock-014",
        "title": "1999 Pokemon Base Set Charizard Holo #4 PSA 8",
        "price": 650.00, "listing_url": "https://www.ebay.com/itm/mock014",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "pokecards4u", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-015",
        "title": "2016 Pokemon XY Evolutions Charizard Holo #11 PSA 10",
        "price": 320.00, "listing_url": "https://www.ebay.com/itm/mock015",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "pokemonmaster", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-016",
        "title": "2023 Pokemon Scarlet Violet Pikachu ex Special Illustration PSA 10",
        "price": 185.00, "listing_url": "https://www.ebay.com/itm/mock016",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "tcgtrader", "condition": "Graded", "is_sold": False,
    },

    # UFC
    {
        "source": "ebay", "external_id": "mock-017",
        "title": "2021 Panini Prizm UFC Conor McGregor Silver PSA 10",
        "price": 140.00, "listing_url": "https://www.ebay.com/itm/mock017",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "mma_cards", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-018",
        "title": "2021 Topps UFC Jon Jones Rookie Auto /50 BGS 9",
        "price": 220.00, "listing_url": "https://www.ebay.com/itm/mock018",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "fightcards101", "condition": "Graded", "is_sold": False,
    },

    # Soccer
    {
        "source": "ebay", "external_id": "mock-019",
        "title": "2004 Panini Lionel Messi Rookie Card Barcelona PSA 8",
        "price": 9800.00, "listing_url": "https://www.ebay.com/itm/mock019",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "soccerlegends", "condition": "Graded", "is_sold": False,
    },
    {
        "source": "ebay", "external_id": "mock-020",
        "title": "2022 Panini Prizm World Cup Kylian Mbappe Gold PSA 10",
        "price": 380.00, "listing_url": "https://www.ebay.com/itm/mock020",
        "image_url": "https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg",
        "seller_name": "worldcupcards", "condition": "Graded", "is_sold": False,
    },

    # NBA (continued)
    {"source":"ebay","external_id":"mock-021","title":"2019-20 Panini Prizm Ja Morant Rookie Silver PSA 10","price":210.00,"listing_url":"https://www.ebay.com/itm/mock021","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"grizzlycards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-022","title":"2019-20 Panini Mosaic Zion Williamson Rookie PSA 10","price":175.00,"listing_url":"https://www.ebay.com/itm/mock022","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pelicansfan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-023","title":"2020-21 Panini Select Lamelo Ball Rookie Concourse PSA 10","price":130.00,"listing_url":"https://www.ebay.com/itm/mock023","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"buzzcards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-024","title":"1996-97 Topps Chrome Kobe Bryant Rookie Refractor PSA 9","price":3800.00,"listing_url":"https://www.ebay.com/itm/mock024","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"mambacards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-025","title":"1997-98 Topps Chrome Tim Duncan Rookie PSA 10","price":520.00,"listing_url":"https://www.ebay.com/itm/mock025","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"spursfan99","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-026","title":"2021-22 Panini Prizm Cade Cunningham Rookie Silver PSA 10","price":85.00,"listing_url":"https://www.ebay.com/itm/mock026","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pistonscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-027","title":"2022-23 Panini Prizm Victor Wembanyama Rookie Silver PSA 10","price":450.00,"listing_url":"https://www.ebay.com/itm/mock027","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"spursnewera","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-028","title":"2007-08 Topps Kevin Durant Rookie Card #2 PSA 9","price":390.00,"listing_url":"https://www.ebay.com/itm/mock028","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"durantfan35","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-029","title":"2012-13 Panini Prizm Anthony Davis Rookie PSA 10","price":195.00,"listing_url":"https://www.ebay.com/itm/mock029","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"unibrow23","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-030","title":"2004-05 Topps Chrome Dwyane Wade Rookie Refractor PSA 9","price":280.00,"listing_url":"https://www.ebay.com/itm/mock030","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"heatnation3","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-031","title":"2003-04 Exquisite Collection Carmelo Anthony Rookie Auto /99 BGS 8","price":620.00,"listing_url":"https://www.ebay.com/itm/mock031","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"melostyle7","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-032","title":"2018-19 Panini Prizm Trae Young Rookie Silver PSA 10","price":160.00,"listing_url":"https://www.ebay.com/itm/mock032","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"hawksfan11","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-033","title":"2023-24 Panini Prizm Wembanyama Kaboom PSA 9","price":890.00,"listing_url":"https://www.ebay.com/itm/mock033","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"kaboomking","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-034","title":"1992-93 Topps Shaquille O'Neal Rookie Card #362 PSA 9","price":145.00,"listing_url":"https://www.ebay.com/itm/mock034","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"shaqattack","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-035","title":"2021-22 Panini National Treasures Evan Mobley Rookie Patch Auto /99","price":310.00,"listing_url":"https://www.ebay.com/itm/mock035","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cavscards","condition":"Near Mint","is_sold":False},

    # NFL (continued)
    {"source":"ebay","external_id":"mock-036","title":"2016 Panini Prizm Dak Prescott Rookie Silver PSA 10","price":145.00,"listing_url":"https://www.ebay.com/itm/mock036","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cowboysnation","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-037","title":"2018 Panini Prizm Lamar Jackson Rookie Silver PSA 10","price":220.00,"listing_url":"https://www.ebay.com/itm/mock037","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"ravensfan8","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-038","title":"2021 Panini Prizm Trevor Lawrence Rookie Silver PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock038","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"jaguarscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-039","title":"2021 Panini Prizm Mac Jones Rookie Silver PSA 10","price":45.00,"listing_url":"https://www.ebay.com/itm/mock039","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"patriotsfan10","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-040","title":"2023 Panini Prizm Bryce Young Rookie Silver PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock040","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"panthercards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-041","title":"2023 Panini Prizm Anthony Richardson Rookie Silver PSA 10","price":48.00,"listing_url":"https://www.ebay.com/itm/mock041","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"coltsfan4","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-042","title":"2020 Panini Prizm Justin Jefferson Rookie Silver PSA 10","price":175.00,"listing_url":"https://www.ebay.com/itm/mock042","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"vikingsfan18","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-043","title":"2020 Panini Prizm Ja'Marr Chase Rookie Silver PSA 10","price":140.00,"listing_url":"https://www.ebay.com/itm/mock043","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"bengalsfan1","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-044","title":"1998 Topps Peyton Manning Rookie Card #360 PSA 9","price":310.00,"listing_url":"https://www.ebay.com/itm/mock044","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"manningfan18","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-045","title":"2011 Panini Prizm Cam Newton Rookie PSA 9","price":85.00,"listing_url":"https://www.ebay.com/itm/mock045","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"panthernation","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-046","title":"2022 Panini Prizm Kenneth Walker III Rookie Silver PSA 10","price":35.00,"listing_url":"https://www.ebay.com/itm/mock046","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"seahawkscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-047","title":"2022 Panini Prizm Garrett Wilson Rookie Silver PSA 10","price":42.00,"listing_url":"https://www.ebay.com/itm/mock047","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"jetsfan17","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-048","title":"2019 Panini Prizm Kyler Murray Rookie Silver PSA 10","price":115.00,"listing_url":"https://www.ebay.com/itm/mock048","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cardinalscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-049","title":"2022 Panini Prizm Drake Maye Rookie Silver PSA 10","price":290.00,"listing_url":"https://www.ebay.com/itm/mock049","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"patriotsnewera","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-050","title":"2005 Topps Chrome Aaron Rodgers Rookie Auto PSA 9","price":780.00,"listing_url":"https://www.ebay.com/itm/mock050","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"packerfan12","condition":"Graded","is_sold":False},

    # MLB (continued)
    {"source":"ebay","external_id":"mock-051","title":"2011 Bowman Chrome Bryce Harper Rookie Auto PSA 10","price":420.00,"listing_url":"https://www.ebay.com/itm/mock051","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"phillies34","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-052","title":"2011 Bowman Chrome Yu Darvish Rookie PSA 10","price":85.00,"listing_url":"https://www.ebay.com/itm/mock052","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cubsfan11","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-053","title":"2018 Topps Update Ronald Acuna Jr Rookie PSA 10","price":195.00,"listing_url":"https://www.ebay.com/itm/mock053","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"bravesfan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-054","title":"2022 Topps Chrome Adley Rutschman Rookie PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock054","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"oriolesfan35","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-055","title":"2023 Topps Chrome Corbin Carroll Rookie Auto PSA 10","price":145.00,"listing_url":"https://www.ebay.com/itm/mock055","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"dbacksfan7","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-056","title":"2019 Topps Chrome Pete Alonso Rookie PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock056","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"metsfan20","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-057","title":"1989 Topps Ken Griffey Jr Rookie Card #1 PSA 9","price":340.00,"listing_url":"https://www.ebay.com/itm/mock057","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"griffeyjr24","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-058","title":"2001 Topps Ichiro Suzuki Rookie Card PSA 9","price":185.00,"listing_url":"https://www.ebay.com/itm/mock058","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"mariners51","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-059","title":"2022 Bowman Chrome Spencer Torkelson 1st Bowman Auto PSA 10","price":78.00,"listing_url":"https://www.ebay.com/itm/mock059","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"tigersfan20","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-060","title":"2023 Topps Chrome Gunnar Henderson Rookie PSA 10","price":90.00,"listing_url":"https://www.ebay.com/itm/mock060","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"oriolesnation","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-061","title":"2016 Topps Chrome Corey Seager Rookie PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock061","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"rangersfan5","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-062","title":"2022 Topps Chrome Jeremy Pena Rookie PSA 10","price":42.00,"listing_url":"https://www.ebay.com/itm/mock062","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"astrosfan3","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-063","title":"2015 Bowman Chrome Kris Bryant Rookie Auto BGS 9.5","price":160.00,"listing_url":"https://www.ebay.com/itm/mock063","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cubsworld","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-064","title":"2014 Topps Update Jacob deGrom Rookie PSA 10","price":95.00,"listing_url":"https://www.ebay.com/itm/mock064","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"metspitching","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-065","title":"1952 Topps Mickey Mantle Card #311 PSA 4","price":32000.00,"listing_url":"https://www.ebay.com/itm/mock065","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"vintagevault","condition":"Graded","is_sold":False},

    # Pokemon (continued)
    {"source":"ebay","external_id":"mock-066","title":"1999 Pokemon Base Set Blastoise Holo #2 PSA 9","price":380.00,"listing_url":"https://www.ebay.com/itm/mock066","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pokevault","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-067","title":"1999 Pokemon Base Set Venusaur Holo #15 PSA 9","price":290.00,"listing_url":"https://www.ebay.com/itm/mock067","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"bulbafan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-068","title":"2002 Pokemon Legendary Collection Charizard Holo #3 PSA 9","price":540.00,"listing_url":"https://www.ebay.com/itm/mock068","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"legendarycollector","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-069","title":"2022 Pokemon Lost Origin Giratina V Alt Art PSA 10","price":220.00,"listing_url":"https://www.ebay.com/itm/mock069","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"altartking","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-070","title":"2023 Pokemon Obsidian Flames Charizard ex Special Illustration PSA 10","price":480.00,"listing_url":"https://www.ebay.com/itm/mock070","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"obsidianflames","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-071","title":"2021 Pokemon Evolving Skies Umbreon VMAX Alt Art PSA 10","price":560.00,"listing_url":"https://www.ebay.com/itm/mock071","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"umbreonfan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-072","title":"1999 Pokemon Jungle Scyther Holo #10 PSA 10","price":1200.00,"listing_url":"https://www.ebay.com/itm/mock072","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"junglecards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-073","title":"2003 Pokemon EX Dragon Rayquaza Holo PSA 9","price":165.00,"listing_url":"https://www.ebay.com/itm/mock073","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"dragonex","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-074","title":"2022 Pokemon Crown Zenith Glaceon VMAX Special Illustration PSA 10","price":195.00,"listing_url":"https://www.ebay.com/itm/mock074","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"crownzenith","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-075","title":"2023 Pokemon 151 Mew ex Special Illustration Raw NM","price":45.00,"listing_url":"https://www.ebay.com/itm/mock075","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"mewcards151","condition":"Near Mint","is_sold":False},
    {"source":"ebay","external_id":"mock-076","title":"1999 Pokemon Base Set Shadowless Charizard PSA 7","price":2800.00,"listing_url":"https://www.ebay.com/itm/mock076","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"shadowlesscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-077","title":"2024 Pokemon Twilight Masquerade Bloodmoon Ursaluna ex Illustration Rare PSA 10","price":130.00,"listing_url":"https://www.ebay.com/itm/mock077","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"twilightcards","condition":"Graded","is_sold":False},

    # NHL
    {"source":"ebay","external_id":"mock-078","title":"2005-06 Upper Deck Sidney Crosby Young Guns Rookie PSA 10","price":1800.00,"listing_url":"https://www.ebay.com/itm/mock078","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"penguinsfan87","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-079","title":"2005-06 Upper Deck Alex Ovechkin Young Guns Rookie PSA 9","price":980.00,"listing_url":"https://www.ebay.com/itm/mock079","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"capsfan8","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-080","title":"2015-16 Upper Deck Connor McDavid Young Guns Rookie PSA 10","price":2400.00,"listing_url":"https://www.ebay.com/itm/mock080","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"oilersfan97","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-081","title":"2021-22 Upper Deck Trevor Zegras Young Guns Rookie PSA 10","price":85.00,"listing_url":"https://www.ebay.com/itm/mock081","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"ducksfan11","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-082","title":"2022-23 Upper Deck Matty Beniers Young Guns Rookie PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock082","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"kraken10","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-083","title":"1979-80 O-Pee-Chee Wayne Gretzky Rookie Card #18 PSA 5","price":8500.00,"listing_url":"https://www.ebay.com/itm/mock083","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"gretzky99","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-084","title":"2022-23 Upper Guns Shane Wright Young Guns Rookie Raw NM","price":18.00,"listing_url":"https://www.ebay.com/itm/mock084","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"kraken4","condition":"Near Mint","is_sold":False},
    {"source":"ebay","external_id":"mock-085","title":"2019-20 Upper Deck Cale Makar Young Guns Rookie PSA 10","price":320.00,"listing_url":"https://www.ebay.com/itm/mock085","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"avsfan8","condition":"Graded","is_sold":False},

    # Soccer (continued)
    {"source":"ebay","external_id":"mock-086","title":"2020 Topps Chrome Erling Haaland Rookie PSA 10","price":420.00,"listing_url":"https://www.ebay.com/itm/mock086","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cityfan9","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-087","title":"2018 Panini Prizm World Cup Kylian Mbappe Rookie PSA 10","price":1100.00,"listing_url":"https://www.ebay.com/itm/mock087","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"psgfan10","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-088","title":"2020 Topps Chrome Pedri Rookie Auto PSA 10","price":185.00,"listing_url":"https://www.ebay.com/itm/mock088","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"barcafan8","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-089","title":"2021 Panini Prizm Jude Bellingham Rookie PSA 10","price":680.00,"listing_url":"https://www.ebay.com/itm/mock089","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"realmadridsupport","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-090","title":"2003 Panini Cristiano Ronaldo Rookie Card Man Utd PSA 7","price":3200.00,"listing_url":"https://www.ebay.com/itm/mock090","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"cr7fan7","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-091","title":"2022 Panini Prizm World Cup Gavi Gold PSA 10","price":145.00,"listing_url":"https://www.ebay.com/itm/mock091","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"spainnt","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-092","title":"2022 Panini Prizm World Cup Vinicius Jr Silver PSA 10","price":195.00,"listing_url":"https://www.ebay.com/itm/mock092","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"brazilcards","condition":"Graded","is_sold":False},

    # UFC (continued)
    {"source":"ebay","external_id":"mock-093","title":"2021 Panini Prizm UFC Israel Adesanya Silver PSA 10","price":95.00,"listing_url":"https://www.ebay.com/itm/mock093","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"ufcfan185","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-094","title":"2021 Panini Prizm UFC Khabib Nurmagomedov Silver PSA 10","price":180.00,"listing_url":"https://www.ebay.com/itm/mock094","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"eaglecards29","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-095","title":"2021 Panini Prizm UFC Sean O'Malley Rookie Silver PSA 10","price":75.00,"listing_url":"https://www.ebay.com/itm/mock095","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"sugasean","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-096","title":"2021 Panini Prizm UFC Alex Pereira Rookie Silver PSA 10","price":120.00,"listing_url":"https://www.ebay.com/itm/mock096","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"poatanfan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-097","title":"2021 Panini Prizm UFC Dustin Poirier Silver PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock097","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"diamondcards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-098","title":"2021 Panini Prizm UFC Charles Oliveira Silver PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock098","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"dolmeifa","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-099","title":"2021 Panini Prizm UFC Amanda Nunes Silver PSA 10","price":80.00,"listing_url":"https://www.ebay.com/itm/mock099","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"lioness37","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-100","title":"2021 Panini Prizm UFC Paddy Pimblett Rookie Silver PSA 10","price":90.00,"listing_url":"https://www.ebay.com/itm/mock100","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"baddiepads","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-101","title":"2021 Panini Prizm UFC Leon Edwards Silver PSA 10","price":70.00,"listing_url":"https://www.ebay.com/itm/mock101","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"rockyufc","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-102","title":"2021 Panini Prizm UFC Francis Ngannou Silver PSA 10","price":85.00,"listing_url":"https://www.ebay.com/itm/mock102","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"predatorcards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-103","title":"2021 Panini Prizm UFC Max Holloway Silver PSA 10","price":60.00,"listing_url":"https://www.ebay.com/itm/mock103","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"blessedcards","condition":"Graded","is_sold":False},

    # NBA - More
    {"source":"ebay","external_id":"mock-104","title":"2021-22 Panini Select Paolo Banchero Rookie Concourse PSA 10","price":95.00,"listing_url":"https://www.ebay.com/itm/mock104","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"magicfan5","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-105","title":"2022-23 Panini Prizm Scoot Henderson Rookie Silver PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock105","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"trailblazerscards","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-106","title":"2023-24 Panini Prizm Brandin Podziemski Rookie Silver PSA 10","price":42.00,"listing_url":"https://www.ebay.com/itm/mock106","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"warriorsfan","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-107","title":"2016-17 Panini Prizm Ben Simmons Rookie Silver PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock107","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"sixersfan25","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-108","title":"2014-15 Panini Prizm Nikola Jokic Rookie Silver PSA 10","price":2100.00,"listing_url":"https://www.ebay.com/itm/mock108","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"nuggsfan15","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-109","title":"2014-15 Panini Prizm Joel Embiid Rookie Silver PSA 10","price":380.00,"listing_url":"https://www.ebay.com/itm/mock109","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"trusttheprocess","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-110","title":"1992-93 Fleer Ultra Shaquille O'Neal Rookie PSA 10","price":280.00,"listing_url":"https://www.ebay.com/itm/mock110","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"lakeshow34","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-111","title":"2001-02 Topps Chrome Yao Ming Rookie PSA 10","price":145.00,"listing_url":"https://www.ebay.com/itm/mock111","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"rocketsfan11","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-112","title":"2023-24 Panini Prizm Chet Holmgren Rookie Silver PSA 10","price":75.00,"listing_url":"https://www.ebay.com/itm/mock112","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"thunderfan7","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-113","title":"2019-20 Panini Prizm RJ Barrett Rookie Silver PSA 10","price":55.00,"listing_url":"https://www.ebay.com/itm/mock113","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"knicksreturn","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-114","title":"2020-21 Panini National Treasures Tyrese Haliburton Rookie Patch Auto /99","price":420.00,"listing_url":"https://www.ebay.com/itm/mock114","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pacersfan0","condition":"Near Mint","is_sold":False},
    {"source":"ebay","external_id":"mock-115","title":"2022-23 Panini Prizm Jalen Williams Rookie Silver PSA 10","price":48.00,"listing_url":"https://www.ebay.com/itm/mock115","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"thunderfan12","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-116","title":"2023-24 Panini Prizm Ausar Thompson Rookie Silver PSA 10","price":38.00,"listing_url":"https://www.ebay.com/itm/mock116","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pistonsfan5","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-117","title":"2021-22 Panini Prizm Franz Wagner Rookie Silver PSA 10","price":52.00,"listing_url":"https://www.ebay.com/itm/mock117","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"magicfan21","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-118","title":"2022-23 Panini Prizm Bennedict Mathurin Rookie Silver PSA 10","price":35.00,"listing_url":"https://www.ebay.com/itm/mock118","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"pacersnation","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-119","title":"2021-22 Panini Prizm Scottie Barnes Rookie Silver PSA 10","price":65.00,"listing_url":"https://www.ebay.com/itm/mock119","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"raptorsfan4","condition":"Graded","is_sold":False},
    {"source":"ebay","external_id":"mock-120","title":"2022-23 Panini Prizm Jabari Smith Jr Rookie Silver PSA 10","price":40.00,"listing_url":"https://www.ebay.com/itm/mock120","image_url":"https://i.ebayimg.com/images/g/iuoAAOSwdAVlmock/s-l500.jpg","seller_name":"rocketsfan10","condition":"Graded","is_sold":False},
]

MOCK_SOLD = [
    {"sold_price": 900.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-28", "source": "ebay"},
    {"sold_price": 820.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-20", "source": "ebay"},
    {"sold_price": 875.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-15", "source": "ebay"},
    {"sold_price": 790.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-10", "source": "ebay"},
    {"sold_price": 950.00, "title": "LeBron James Rookie PSA 9", "sold_at": "2026-05-01", "source": "ebay"},
    {"sold_price": 3400.00, "title": "Curry Prizm Rookie PSA 10", "sold_at": "2026-05-25", "source": "ebay"},
    {"sold_price": 3100.00, "title": "Curry Prizm Rookie PSA 10", "sold_at": "2026-05-18", "source": "ebay"},
    {"sold_price": 320.00, "title": "Mahomes Prizm Rookie PSA 10", "sold_at": "2026-05-29", "source": "ebay"},
    {"sold_price": 295.00, "title": "Mahomes Prizm Rookie PSA 10", "sold_at": "2026-05-22", "source": "ebay"},
    {"sold_price": 5800.00, "title": "Trout Bowman Chrome Auto PSA 10", "sold_at": "2026-05-27", "source": "ebay"},
    {"sold_price": 700.00, "title": "Charizard Base Set PSA 8", "sold_at": "2026-05-26", "source": "ebay"},
    {"sold_price": 620.00, "title": "Charizard Base Set PSA 8", "sold_at": "2026-05-19", "source": "ebay"},
]
